pgsql.lo: /root/server/php-pgsql-5.6/pgsql.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/server/php-pgsql-5.6 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/server/php-pgsql-5.6/pgsql.c -o pgsql.lo 
$(phplibdir)/pgsql.la: ./pgsql.la
	$(LIBTOOL) --mode=install cp ./pgsql.la $(phplibdir)

./pgsql.la: $(shared_objects_pgsql) $(PGSQL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_pgsql) $(PGSQL_SHARED_LIBADD)

